spring:
  application:
    name: chat-service
  profiles:
    active: none
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  cloud:
    config:
      profile: ${PROFILE}
  kafka:
    consumer:
      group-id: payment-consumer
encrypt:
  key: ${ENCRYPT_KEY}